name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@722adc6
      with:
        fetch-depth: 0
    - name: Fetch origin/master for SonarQube analysis
      # https://community.sonarsource.com/t/sonarcloud-now-not-updating-github-pr-and-checks/6595/17

      # Use the same URL as remote repo with actions/checkout. Expect that github.repository does not need encodeURIComponent
      # https://github.com/actions/checkout/blob/a6747255bd19d7a757dbdda8c654a9f84db19839/src/git-source-provider.ts#L32-L34
      run: git fetch --no-tags https://github.com/${{ github.repository }} +refs/heads/master:refs/remotes/origin/master
    - name: Set up JDK 11
      uses: actions/setup-java@081536e
      with:
        java-version: 11
    - name: Set up Node.js 12
      uses: actions/setup-node@8de2f9f
      with:
        node-version: 12
    - uses: actions/cache@cffae95
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@cffae95
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build with Gradle
      run: ./gradlew build sonarqube -Dsonar.login=${{ secrets.SONAR_LOGIN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Semantic Release
      run: |
        echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" > ~/.gradle/gradle.properties
        echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties
        yarn
        yarn semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@3446296
      if: always()
      with:
        name: reports
        path: build/reports
